const express=require('express')
const { deleteAllProducts,createProduct, getAllProducts, getProduct, updateProduct, addToWishlist, deleteProductById, rating, getProductByCategory} = require('../controller/productController')
const router=express.Router()
const {auth,isAdmin}=require('../middlewares/auth')
const {productValidation} = require('../utils/validateJoi')

router.post('/',productValidation, createProduct)
router.put('/wishlist',auth, addToWishlist)
router.put('/rating',auth,rating)
router.put('/:id', updateProduct)
router.delete('/:id', deleteProductById)
router.get('/category/:category', getProductByCategory)
router.get('/:id', getProduct)
router.get('/', getAllProducts)
router.delete('/', deleteAllProducts)
module.exports=router